---
title: "R Notebook"
output: html_notebook
---

# Movie Recommendation System
Build a recommendation engine that recommends movies to users. Item Based Collaborative Filter recommendation system.
```{r}
library(recommenderlab)
library(ggplot2)                       
library(data.table)
library(reshape2)
```
```{r}
# Retrieve and display data
movie_data <- read.csv("/Users/tahaberkterekli/Documents/GitHub/R/projects/Movie Recommendation System/IMDB-Dataset/movies.csv",stringsAsFactors=FALSE)
rating_data <- read.csv("/Users/tahaberkterekli/Documents/GitHub/R/projects/Movie Recommendation System/IMDB-Dataset/ratings.csv")
str(movie_data)
```
```{r}
summary(movie_data)
head(movie_data)
summary(rating_data)
head(rating_data)
```
```{r}
# Data pre-processing
# Creating a one-hot encoding to create a matrix that comprises of corresponding genres for each of the films.
movie_genre <- as.data.frame(movie_data$genres, stringsAsFactors = FALSE)
library(data.table)
movie_genre2 <- as.data.frame(tstrsplit(movie_genre[,1], '[|]',
                                        type.convert = TRUE),
                              stringAsFactors=FALSE)
colnames(movie_genre2) <- c(1:10)
list_genre <- c("Action", "Adventure", "Animation", "Children", 
                "Comedy", "Crime","Documentary", "Drama", "Fantasy",
                "Film-Noir", "Horror", "Musical", "Mystery","Romance",
                "Sci-Fi", "Thriller", "War", "Western")
genre_mat1 <- matrix(0,10330,18)
genre_mat1[1,] <- list_genre
colnames(genre_mat1) <- list_genre
for (index in 1:nrow(movie_genre2)) {
  for (col in 1:ncol(movie_genre2)) {
    gen_col = which(genre_mat1[1,] == movie_genre2[index, col])
    genre_mat1[index+1,gen_col] <- 1
  }
}
genre_mat2 <- as.data.frame(genre_mat1[-1,], stringsAsFactors=FALSE) #remove first row, which was the genre list
for (col in 1:ncol(genre_mat2)) {
  genre_mat2[,col] <- as.integer(genre_mat2[,col]) #convert from characters to integers
} 
str(genre_mat2)
```
```{r}
# Creating a ‘search matrix’ - searching films by specifying the genre
SearchMatrix <- cbind(movie_data[,1:2], genre_mat2[])
head(SearchMatrix)
ratingMatrix <- dcast(rating_data, userId~movieId, value.var = "rating", na.rm = FALSE)
ratingMatrix <- as.matrix(ratingMatrix[,-1]) #remove userIds
# Convert rating matrix into a recommenderlab sparse matrix
ratingMatrix <- as(ratingMatrix, "realRatingMatrix")
ratingMatrix
```

